### ISSUE TITLE
openprocure: search results should include item's status

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-search#121]
results list should include an indication (label?) of the item's status

https://next.obudget.org/s/?q=%D7%94%D7%A1%D7%A2%D7%95%D7%AA&dd=all&range=all&theme=govbuy:

![image](https://user-images.githubusercontent.com/3581741/43040518-6b86e1fc-8d4e-11e8-8e0c-e70b5faadd25.png)

**Comment by akariv** [comment]
This is the current design... where should I add that?

![Screen Shot 2018-07-22 at 15.29.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537482f6ebef97b1f959d236/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f16b7191a379ea0c2958415f4abe5d4a1f06a3a3dc78e2a436628f540de4d96b5d7c943b19aebdd01eb701ba21dd4d8dbee99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb5af44de34853a3143f64f43b.png)

**Comment by noamoss** [comment]
@mushon ^^^

**Comment by mushon** [comment]
Label added:
https://projects.invisionapp.com/d/main#/console/7587193/253951995/inspect

![image](https://user-images.githubusercontent.com/27123/43092456-f12d0eb8-8eb5-11e8-94a4-bacbef204393.png)

**Comment by noamoss** [comment]
@akariv ready for development. Notice we are talking here about the 'simple status' for the new label.
