### ISSUE TITLE
open procure: fix tenders and exemptions short status label (4 categories)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-search#124]
watching all the central tenedrs of a query ("שירות" for example) I can see an open  tender:
https://next.obudget.org/s/?q=%D7%A9%D7%99%D7%A8%D7%95%D7%AA&dd=central-tenders&range=all&theme=govbuy&focused=no

![image](https://user-images.githubusercontent.com/3581741/43520863-e6e3fb72-959c-11e8-8e0f-8839106e7826.png)

but when I filter to show ONLY open cetnral tenders I get "none":
https://next.obudget.org/s/?q=%D7%A9%D7%99%D7%A8%D7%95%D7%AA&dd=central-tenders&range=all&theme=govbuy&focused=open

![image](https://user-images.githubusercontent.com/3581741/43520851-d5c88d1c-959c-11e8-8f05-4a161f00b265.png)

**Comment by akariv** [comment]
Click on the related tender - it closed 6 months ago. It is definitely not open.
The 'decision' field is 'פורסם וממתין לתוצאות', which for some reason is translated to 'פתוח'...
The 'open' filter works by comparing the claim date (last date to apply) and the current date.

**Comment by noamoss** [comment]
@akariv Thanks, I admit missing it. 

> The 'decision' field is 'פורסם וממתין לתוצאות', which for some reason is translated to 'פתוח'...

this is how I understood this label. would you prefer using "עבר תאריך ההגשה"?

**Comment by noamoss** [comment]
The problem is that it is not marked in the data source as closed... correct me if I am wrong.

**Comment by akariv** [comment]
No, the data source is correct. The tender is indeed closed, and is waiting
for results to be published.
The translation table marks this state as being 'open' while it's not.

**Comment by akariv** [comment]
Perhaps we need a distinction between
מכרז פתוח - אפשר להגיש
מכרז סגור - אי אפשר להגיש
מכרז הסתיים - נגמר התהליך
מכרז פעיל - קיימות התקשרויות פעילות מהמכרז

בכל מקרה ההגדרה של הפילטר ״מכרזים פתוחים״היא מדויקת ומחוברת להגדרה של
״נסגרים בקרוב״.
נסגרים בקרוב הם כל אלו שמועד ההגשהשלהם בשבוע הקרוב. ההגיון מחייב שאחרי מועד
הסגירה המכרז הופך לסגור...

**Comment by noamoss** [comment]
@akariv great, we will stick to that:

> מכרז פתוח - אפשר להגיש מכרז סגור - אי אפשר להגיש מכרז הסתיים - נגמר התהליך מכרז פעיל - קיימות התקשרויות פעילות מהמכרז

I will update the table on Monday.

**Comment by noamoss** [comment]
@akariv 

fixed the relevant line the definition line.

adding the פעיל status is problematic due to weird combinations of (like open and active tender, or canceled and active tenders). I don't see a way showing it without confusing the users.

Please review [the table](https://docs.google.com/spreadsheets/d/1JkZooBwoxKPlrXWWwUtNHLMdxc-iG0n5tdGZ23I8fYY/edit#gid=1250185114) before we deploy it, I am not certain about all the changes I made.

**Comment by akariv** [comment]
Did you also review OpenBudget/BudgetKey#200 and added the missing items?

**Comment by akariv** [comment]
Active _contracts_ (which I assume you  meant) could be the result of bad Manof refs in the contracts data (which we know is not uncommon).
I would suggest ignoring active contract flags in cases where it doesn't make sense with the tender state.

**Comment by akariv** [comment]
Writing here what we discussed in person:
Ignore it in the google spreadsheet.
e.g. if a contract is open and also has active contract (although it shouldn't have those, as it's still open), just assume that these contracts are garbage-matches and not something that needs to be considered.
