### ISSUE TITLE
budget item children

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/budgetkey-app-search#17]
retrieve all the children per budget item - adam - from elastic
needs the code + type per each child

add to design the child in the bottom footer
תחומים מתקנה זו, פטורים, רכש וכו
ומספר תקנות שכר

**Comment by akariv** [comment]
Children are already in the returned data (in the `children` field).
Aggregation of economic classifications is in the `econ_cls_*` fields

**Comment by YontiLevin** [comment]
sorry. my bad. now i see it
next week we will add that to the bottom footer

**Comment by akariv** [comment]
+1

**Comment by YontiLevin** [comment]
assigned to @YoniH
