### ISSUE TITLE
Should show some loading indication while fetching results

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-search#22]

**Comment by akariv** [comment]
@mushon can you spec this a bit more (I'm thinking - some spinner inside the search box, near the spying glass)

**Comment by akariv** [comment]
Also - need an indication for "no results received" and "error fetching results"

**Comment by YontiLevin** [comment]
merged the pull request
functionality wise it working great
design wise ...
@mushon your help is needed here
not closing yet

**Comment by mushon** [comment]
attaching loader animation:
[loader.svg.zip](https://github.com/OpenBudget/budgetkey-app-search/files/1133805/loader.svg.zip)

it should replace the lupe when loading like this:
![image](https://user-images.githubusercontent.com/27123/27994746-19bae70c-64cc-11e7-982c-d73a863c0445.png)
