### ISSUE TITLE
contract spending multiple similar results for the same provider and the same office

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/budgetkey-app-search#23]
in the contract spending we are multiple similar results for the same provider and the same office.
the items differ by year
we should do something similar to what was done in the budget

@akariv lets review this together monday

**Comment by akariv** [comment]
Could you give here a few examples?
(Also cc-ing @saaralonbarkat)

**Comment by YontiLevin** [comment]
![takziv](https://user-images.githubusercontent.com/18164633/27370439-3ee699a6-5665-11e7-8a9b-9da00c615b28.png)

**Comment by YontiLevin** [comment]
look at the first 2
we can also talk about the second 2

**Comment by akariv** [comment]
Interesting... I guess there are other suppliers for which there could be very different services being purchased. I wonder if these should be aggregated as well.
(also: Saar - ignore the design, these are actually התקשרויות רכש).

**Comment by YontiLevin** [comment]
![my-meme](https://user-images.githubusercontent.com/18164633/27370722-83cd460e-5666-11e7-9421-25aed30c7ae7.jpg)

**Comment by akariv** [comment]
<img width="614" alt="screen shot 2017-06-24 at 22 14 25" src="https://user-images.githubusercontent.com/265333/27511360-8b9cbb78-592a-11e7-8a19-4eb0d9f0d80f.png">

**Comment by saaralonbarkat** [comment]
תנו לי להסביר: כל ביצוע של אגרגציה לנתונים של הפטורים, ידרוש לקחת החלטות שרירותיות. לפעמים אין ברירה לעשות, אבל בחיפוש החופשי, עדיף לדעתי פשוט להראות את הלינקים לרשומות הגולמיות.
