### ISSUE TITLE
contract spending - use 'entity_name' and 'entity_id'

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-search#24]
Prefer to use 'entity_name' and 'entity_id' Instead of 'supplier' and 'supplier_name'.
Only if the first two are empty, fall back to the 'supplier' ones.

**Comment by danielbraun** [comment]
I'm on it

**Comment by shaylavi** [comment]
is that the object that's returning from the search results? cause I'm using the "supplier" object in the new highlight component

**Comment by akariv** [comment]
Yes, we should be using the 'entity_name' whenever it's available.
