### ISSUE TITLE
[Search] [Exemption] Design and implement exemption item

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-search#27]
now returning as `exemptions`

**Comment by YontiLevin** [comment]
#11 
@shaylavi
check that 👆 issue
it explains the difference between the two kinds of רכש

**Comment by shaylavi** [comment]
I'm gonna leave this - I wasted way too much time on it and I can't find a way to do it without leaving a big mess

**Comment by OriHoch** [comment]
I'll have a go at it

**Comment by OriHoch** [comment]
![image](https://user-images.githubusercontent.com/1198854/29750088-78acd634-8b42-11e7-9090-12a44bb66d5d.png)

**Comment by OriHoch** [comment]
after PR #68 is merged, it should be displayed with correct template, but still, I guess some more design work is needed

![image](https://user-images.githubusercontent.com/1198854/29750296-ce563a82-8b45-11e7-9fcd-b65140db1c6c.png)

**Comment by mushon** [comment]
Ori, can you be more specific?

**Comment by OriHoch** [comment]
If the screenshot I added above looks good to you, then no more design is needed

**Comment by mushon** [comment]
ok, gotchya…
@saaralonbarkat is this a bug or a (problematic-design-for-a) feature?
![image](https://user-images.githubusercontent.com/1198854/29750296-ce563a82-8b45-11e7-9fcd-b65140db1c6c.png)

**Comment by YontiLevin** [comment]
@OriHoch 
i approved your PR
but it doesn't look like the screenshot you attached above
didn't see in the commit any html files
also, the exemptions and contractspending go it the same tab
inside the tab they should differ in color and text
like we have in the entities - many organizations types under the same tab but different design for each

**Comment by OriHoch** [comment]
looking at the site now, it seems to work correctly, as in my screenshot above

![image](https://user-images.githubusercontent.com/1198854/29760829-9e26bc04-8bce-11e7-85fd-61372298dc19.png)

now, just need to have the design that will differentiate between exemptions and the cotractspending

A color hex for the vertical title on the right would be enough IMO

**Comment by OriHoch** [comment]
regarding the exemptions html template - it was already there.. just wasn't used anywhere
