### ISSUE TITLE
Search spinner doesn't rotate on Safari

### ISSUE THREAD

**Issue by danielbraun** [OpenBudget/budgetkey-app-search#42]
How to reproduce:
1. Search anything using Safari on Mac

If the current spinner is problematic, the spinners at http://fontawesome.io/examples/#animated work well.

<img width="52" alt="spinner_bug" src="https://user-images.githubusercontent.com/1410895/28037250-6d28cc7c-65c3-11e7-91aa-1614769b2ea3.png">

**Comment by YoniH** [comment]
It seems that the loader itself is fine. Maybe the UI thread is choked by a long running task?

**Comment by YoniH** [comment]
Can't reproduce on my computer, we saw this only on @danielbraun 's computer
