### ISSUE TITLE
people - once pressed breaks the search

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/budgetkey-app-search#63]
can't switch tabs and so
@aviklai lets go over it together next week

**Comment by aviklai** [comment]
@YontiLevin  - I fixed it and opened a pull request - the $event parameter was missing in the switchTab of the people tab.

**Comment by YontiLevin** [comment]
@aviklai notice that i commented out some parts (slice and such) which were not relevant to this group and were only in the code because it is referencing the entities group. so git pull before you continue working
