### ISSUE TITLE
Implement new design for search result cards

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/budgetkey-app-search#79]
we got a new design waiting for implementation 
here's the link to the mockup:
https://projects.invisionapp.com/d/main/default/#/console/7587193/253951995/preview

there are three object types which need new template design:
1.budget
2.entities
3.other

reach me next meeting and i'll go over it with you
(and grant you invision permissions if it doe'snt work for you)

**Comment by OriHoch** [comment]
@YontiLevin please grant me permissions.. thanks

**Comment by YontiLevin** [comment]
@OriHoch sent you an invitation to ori@uumpa.com
if you want a diff mail address just say

**Comment by markfridman** [comment]
@YontiLevin  please grant me permissions as well at mark@misterbit.co.il
thanks
