### ISSUE TITLE
search missions for the hackaton

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/budgetkey-app-search#8]
hi all,
starting a list of the missions needed to be done for the search to launch:

1. retrieve all categories from the data packages
    a. now we only have entities, budget & contract-spending - @akariv 
    b. what is contract-spending?
    c. make sure that all available fields return in each category  
2. review the div design for each category - @mushon
    a. make sure that the design meets the actual fields that return - @mushon & me
3. fill in all the returned fields per category into the divs - me
4. fix infinte scroll - me
    a. when a new batch of results return it is arranged by category - this makes an annoying jump
    b. to do - change the paradigm from if for to for if 
5. scroll the results div only and not the entire window - me
6. hierarchy for returned results - @joroizin 
    a. think of the order of the returned results and implement it in elastic
    b. for example, first display exact matches then similar...

that's just of the top of my head
i suggest sitting together in the beginning of the hackaton to review and add more tasks
add your own comments and tasks bellow

**Comment by akariv** [comment]
1. 
a. I will add monetary changes pretty soon. Supports and exemptions are a bit stuck.
b. רכש ממשלתי
c. Slowly getting there...
6. I will add an "amount  of money" figure which should be a natural sorting measure (usually the more money is involved, the more interesting things are)
