### ISSUE TITLE
time line/ filter

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/budgetkey-app-search#81]
reflect num of results per year 
check new design at
https://projects.invisionapp.com/d/main/default/#/console/7587193/253951995/preview

1. should open up on 2017
2. hover- set borders(which are draggable) 
3. when the option chosen is last 7/30 days - time line expends - @mushon will create an example for you
4. when range is chosen - a calendar opens up

**Comment by simonbor** [comment]
@akariv could you show me what the place for the timeline bar? 
Thanks a lot!

**Comment by simonbor** [comment]
@akariv In which place would you suggest to hold combo items? 
![image](https://user-images.githubusercontent.com/8211293/35068167-eafed90a-fbde-11e7-9a47-642363769fb6.png)
Some kind of `config.json`?

**Comment by OriHoch** [comment]
I'm working on the backend to support this

**Comment by OriHoch** [comment]
added the counts per month/year, 
some results only have a year, so in the UI you can just show them under January. of that year
also, the results are per doc-type, leaving it to frontend to do the aggregation of all doc types if needed

the result from search api will look like this:
```
{
  search_counts: {
    supports: {
      total_overall: 1292,
      year_counts: {
        2009: 5,
        2010: 5,
        2011: 6
      }
    },
  tenders: {
    month_counts: {
      2016-08: 1,
      2017-07: 2,
      2017-09: 1,
      2017-11: 1
  },
  total_overall: 5
}}, search_results: [...]}
```
